import { config } from '../../server/config'; import { state } from '../../server/state'; import { serverEnv } from '../../config/env'; import { syncUsersToDb } from '../../lib/db/usersRepo';
type Result<T>={status:number;body:T}; type ErrorBody={error?:string;code?:string;message?:string};
const configured=Object.values({tenantId:serverEnv.microsoftTenantId,clientId:serverEnv.microsoftClientId,clientSecret:serverEnv.microsoftClientSecret,redirectUri:serverEnv.microsoftRedirectUri}).every(Boolean);
export function authConfig(){return {status:200,body:{provider:'microsoft',mode:config.authMode,demoModeEnabled:config.demoMode,demoLoginEnabled:config.enableDemoLogin,microsoft:{configured,loginUrl:'/api/auth/microsoft/start'}}};}
export function microsoftStart():Result<ErrorBody>{return configured?{status:501,body:{code:'MICROSOFT_AUTH_ADAPTER_REQUIRED',message:'Entra settings are present. Install the approved OIDC session adapter before enabling Microsoft sign-in.'}}:{status:503,body:{code:'MICROSOFT_AUTH_NOT_CONFIGURED',message:"Microsoft sign-in is awaiting the organization's Entra app registration."}};}
export function demoUsers():Result<unknown>{return config.enableDemoLogin?{status:200,body:state.users.map(({id,name,email,role,department,job_title,avatar_url})=>({id,name,email,role,department,job_title,avatar_url}))}:{status:404,body:{error:'Demo login is disabled.'}};}
export function login(email:string):Result<unknown>{const user=state.users.find((candidate)=>candidate.email===email);return user?{status:200,body:user}:{status:401,body:{error:'User not found'}};}
export function me(userId:string|null):Result<unknown>{const user=state.users.find((candidate)=>candidate.id===userId||candidate.entra_object_id===userId||candidate.user_principal_name===userId);return user?{status:200,body:user}:{status:401,body:{error:'Unauthorized'}};}
export async function notificationPrefs(userId:string|null,prefs:unknown):Promise<Result<unknown>>{const user=state.users.find((candidate)=>candidate.id===userId||candidate.entra_object_id===userId||candidate.user_principal_name===userId);if(!user)return {status:401,body:{error:'Unauthorized'}};user.notification_prefs=prefs as typeof user.notification_prefs;try{await syncUsersToDb(state.users)}catch(error){console.error('[db] Could not persist notification preferences to Postgres:',error)}return {status:200,body:user.notification_prefs};}
