import { CashAdvanceStatus, Liquidation, LiquidationStatus, LiquidationVarianceType, User, UserRole } from '../../lib/db/serverTypes';
import { v4 as uuidv4 } from 'uuid';
import { checkCategoryLimits, state } from '../../server/state';
import { canAccessLiquidation } from '../../server/services/authorization';
import { isActiveDelegateFor } from '../../server/services/delegations';
import { isFinanceVisibleFinancialRecord } from '../../server/constants';
import { persistCashAdvance, persistLiquidation, persistLiquidationLineItems } from '../../lib/db/cashAdvanceRepo';
import { addCaHistory, addLiqHistory } from '../../server/services/history';
import { isClaimTypeEnabled, COMING_SOON_MESSAGE } from '../featureFlags';
import { normalizeExpenseCategory } from '../../lib/expenseCategories';

type ErrorBody = { error: string }; type Result<T> = { status: number; body: T };
function userFor(id: string | null): User | undefined { return state.users.find((user) => user.id === id || user.entra_object_id === id || user.user_principal_name === id); }
function canList(user: User, liquidation: Liquidation) { const advance = state.cashAdvances.find((candidate) => candidate.id === liquidation.cashAdvanceId); return user.role === UserRole.REQUESTOR ? liquidation.requestorId === user.id : user.role === UserRole.APPROVER ? liquidation.requestorId === user.id || advance?.approverId === user.id || state.users.some((candidate) => candidate.id === liquidation.requestorId && candidate.reports_to === user.id) || isActiveDelegateFor(user.id, advance?.approverId) : user.role === UserRole.FINANCE ? isFinanceVisibleFinancialRecord('Liquidation', liquidation.status) : true; }
function enrich(liquidation: Liquidation, changedBy = false) { const cashAdvance = state.cashAdvances.find((advance) => advance.id === liquidation.cashAdvanceId); return { ...liquidation, requestor: state.users.find((user) => user.id === liquidation.requestorId), cashAdvance, mom: cashAdvance?.momId ? state.moms.find((mom) => mom.id === cashAdvance.momId) : undefined, lineItems: state.liquidationLineItems.filter((item) => item.liquidationId === liquidation.id), history: state.statusHistories.filter((entry) => entry.liquidation_id === liquidation.id).map((entry) => changedBy ? { ...entry, changedBy: state.users.find((user) => user.id === entry.changed_by) } : entry).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()) }; }
export async function recalculateLiquidation(id: string) { const liquidation = state.liquidations.find((candidate) => candidate.id === id); const advance = liquidation && state.cashAdvances.find((candidate) => candidate.id === liquidation.cashAdvanceId); if (!liquidation || !advance) return; const items = state.liquidationLineItems.filter((item) => item.liquidationId === id); liquidation.totalSpent = items.reduce((total, item) => total + item.amount, 0); liquidation.varianceAmount = liquidation.totalSpent - advance.amount; liquidation.varianceType = liquidation.varianceAmount === 0 ? LiquidationVarianceType.SETTLED : liquidation.varianceAmount < 0 ? LiquidationVarianceType.REFUND_DUE : LiquidationVarianceType.REIMBURSEMENT_DUE; try { await persistLiquidation(liquidation); await persistLiquidationLineItems(id, items); } catch (error) { console.error('[db] Could not persist recalculated liquidation to Postgres:', error); } }
export function listLiquidations(userId: string | null): Result<Array<ReturnType<typeof enrich>> | ErrorBody> { const user = userFor(userId); return !user ? { status: 401, body: { error: 'Unauthorized' } } : { status: 200, body: state.liquidations.filter((liquidation) => canList(user, liquidation)).map((liquidation) => enrich(liquidation)) }; }
export function getLiquidation(userId: string | null, id: string): Result<ReturnType<typeof enrich> | ErrorBody> { const user = userFor(userId); if (!user) return { status: 401, body: { error: 'Unauthorized' } }; const liquidation = state.liquidations.find((candidate) => candidate.id === id); if (!liquidation) return { status: 404, body: { error: 'Liquidation not found' } }; if (!canAccessLiquidation(user, liquidation)) return { status: 403, body: { error: 'Forbidden' } }; return { status: 200, body: enrich(liquidation, true) }; }
export async function createLiquidation(userId: string | null, input: { cashAdvanceId?: string }): Promise<Result<Liquidation | ErrorBody>> { const user = userFor(userId); if (!user) return { status: 401, body: { error: 'Unauthorized' } }; if (user.role === UserRole.FINANCE) return { status: 403, body: { error: 'Finance access is view-only.' } }; if (!isClaimTypeEnabled('Liquidation')) return { status: 403, body: { error: COMING_SOON_MESSAGE } }; if (!input.cashAdvanceId) return { status: 400, body: { error: 'Cash Advance ID is required.' } }; const advance = state.cashAdvances.find((candidate) => candidate.id === input.cashAdvanceId); if (!advance) return { status: 404, body: { error: 'Cash Advance not found' } }; if (advance.requestorId !== user.id) return { status: 403, body: { error: 'You can only liquidate your own Cash Advances.' } }; if (advance.status !== CashAdvanceStatus.RELEASED) return { status: 400, body: { error: 'You can only liquidate Cash Advances that have been Released.' } }; if (state.liquidations.some((candidate) => candidate.cashAdvanceId === advance.id)) return { status: 400, body: { error: 'A Liquidation already exists for this Cash Advance.' } }; const liquidation: Liquidation = { id: uuidv4(), cashAdvanceId: advance.id, requestorId: user.id, totalSpent: 0, varianceAmount: -advance.amount, varianceType: LiquidationVarianceType.REFUND_DUE, status: LiquidationStatus.DRAFT, createdAt: new Date().toISOString() }; state.liquidations.push(liquidation); try { await persistLiquidation(liquidation); } catch (error) { console.error('[db] Could not persist new liquidation to Postgres:', error); } addLiqHistory(liquidation.id, '', LiquidationStatus.DRAFT, user.id, 'Liquidation Draft Started'); addCaHistory(advance.id, advance.status, advance.status, user.id, 'Liquidation Started'); return { status: 200, body: liquidation }; }

function editable(userId: string | null, id: string): Result<Liquidation | ErrorBody> { const user = userFor(userId); const liquidation = state.liquidations.find((candidate) => candidate.id === id); if (!user) return { status: 401, body: { error: 'Unauthorized' } }; if (!liquidation) return { status: 404, body: { error: 'Liquidation not found' } }; if (liquidation.requestorId !== user.id) return { status: 403, body: { error: 'You do not have permission to modify this Liquidation.' } }; if (![LiquidationStatus.DRAFT, LiquidationStatus.RETURNED_FOR_REVISION].includes(liquidation.status)) return { status: 400, body: { error: 'This Liquidation is read-only because it has been submitted.' } }; return { status: 200, body: liquidation }; }
export async function addLiquidationLineItem(userId: string | null, id: string, input: any): Promise<Result<any>> { const found = editable(userId, id); if (found.status !== 200) return found; const required = ['expense_date','vendor','category','amount','payment_method','business_purpose','receipt_url']; if (required.some((key) => input[key] === undefined || input[key] === '')) return { status: 400, body: { error: 'Missing required expense fields.' } }; const amount = Number(input.amount); if (!Number.isFinite(amount) || amount <= 0) return { status: 400, body: { error: 'Amount must be a valid number greater than zero.' } }; const item = { id: uuidv4(), liquidationId: id, expense_date: input.expense_date, vendor: input.vendor, category: normalizeExpenseCategory(input.category), amount, payment_method: input.payment_method, business_purpose: input.business_purpose, receipt_url: input.receipt_url, attachment_type: input.attachment_type || 'Official Receipt', or_number: input.or_number || undefined }; state.liquidationLineItems.push(item); await recalculateLiquidation(id); return { status: 200, body: item }; }
export async function updateLiquidationLineItem(userId:string|null,id:string,itemId:string,input:any):Promise<Result<any>> { const found=editable(userId,id); if(found.status!==200)return found; const item=state.liquidationLineItems.find((x)=>x.id===itemId&&x.liquidationId===id); if(!item)return {status:404,body:{error:'Line item not found'}}; Object.assign(item,input); if(input.category!==undefined)item.category=normalizeExpenseCategory(input.category); if(input.amount!==undefined){const n=Number(input.amount);if(!Number.isFinite(n)||n<=0)return {status:400,body:{error:'Amount must be a valid number greater than zero.'}};item.amount=n;} await recalculateLiquidation(id);return {status:200,body:item}; }
export async function deleteLiquidationLineItem(userId:string|null,id:string,itemId:string):Promise<Result<any>> { const found=editable(userId,id);if(found.status!==200)return found;const index=state.liquidationLineItems.findIndex((x)=>x.id===itemId&&x.liquidationId===id);if(index<0)return {status:404,body:{error:'Line item not found'}};state.liquidationLineItems.splice(index,1);await recalculateLiquidation(id);return {status:200,body:{success:true}}; }
export async function submitLiquidation(userId:string|null,id:string,input:{refundMethod?:string}):Promise<Result<any>> { const user=userFor(userId);if(!user)return {status:401,body:{error:'Unauthorized'}};const liquidation=state.liquidations.find((x)=>x.id===id&&x.requestorId===user.id);if(!liquidation)return {status:404,body:{error:'Liquidation not found'}};if(![LiquidationStatus.DRAFT,LiquidationStatus.RETURNED_FOR_REVISION].includes(liquidation.status))return {status:400,body:{error:'Only Liquidations in Draft or ReturnedForRevision status can be submitted.'}};const policy=checkCategoryLimits(state.liquidationLineItems.filter((x)=>x.liquidationId===id));if(policy)return {status:400,body:{error:policy}};await recalculateLiquidation(id);if(input.refundMethod&&liquidation.varianceType===LiquidationVarianceType.REFUND_DUE)liquidation.refundMethod=input.refundMethod;const old=liquidation.status;liquidation.status=LiquidationStatus.SUBMITTED;addLiqHistory(id,old,LiquidationStatus.SUBMITTED,user.id,'Liquidation Submitted for Review');try{await persistLiquidation(liquidation)}catch(error){console.error('[db] Could not persist liquidation submission to Postgres:',error)}return {status:200,body:liquidation}; }
export async function reviewLiquidation(userId:string|null,id:string,input:{decision?:string;comment?:string}):Promise<Result<any>> { const user=userFor(userId);if(!user||user.role!==UserRole.APPROVER)return {status:403,body:{error:'Forbidden'}};const l=state.liquidations.find(x=>x.id===id);if(!l)return {status:404,body:{error:'Liquidation not found'}};const ca=state.cashAdvances.find(x=>x.id===l.cashAdvanceId);if(!ca||(ca.approverId!==user.id&&!isActiveDelegateFor(user.id,ca.approverId)))return {status:403,body:{error:'You are not the designated approver/reviewer for this Liquidation.'}};if(l.status!==LiquidationStatus.SUBMITTED)return {status:400,body:{error:'Only Submitted Liquidations can be reviewed.'}};if(input.decision!=='Returned'&&input.decision!=='Approved')return {status:400,body:{error:'Invalid decision. Must be Approved or Returned.'}};if(input.decision==='Returned'&&!input.comment)return {status:400,body:{error:'A comment is required when returning a Liquidation for revision.'}};await recalculateLiquidation(id);const old=l.status;if(input.decision==='Returned'){l.status=LiquidationStatus.RETURNED_FOR_REVISION;addLiqHistory(id,old,l.status,user.id,input.comment||'Returned for revision');}else{l.status=l.varianceType===LiquidationVarianceType.REFUND_DUE?LiquidationStatus.REVIEWED:LiquidationStatus.CLOSED;ca.status=CashAdvanceStatus.LIQUIDATED;addLiqHistory(id,old,l.status,user.id,'Liquidation Approved');addCaHistory(ca.id,ca.status,CashAdvanceStatus.LIQUIDATED,user.id,'Liquidation Reviewed');}try{await persistLiquidation(l);await persistCashAdvance(ca)}catch(error){console.error('[db] Could not persist liquidation review to Postgres:',error)}return {status:200,body:l}; }
export async function collectLiquidationRefund(userId:string|null,id:string,input:{referenceNote?:string;refundMethod?:string}):Promise<Result<any>> { const user=userFor(userId);if(!user||user.role!==UserRole.CUSTODIAN)return {status:403,body:{error:'Forbidden: Only Custodians can collect refunds.'}};const l=state.liquidations.find(x=>x.id===id);if(!l)return {status:404,body:{error:'Liquidation not found'}};if(l.status!==LiquidationStatus.REVIEWED)return {status:400,body:{error:'Only Reviewed Liquidations with pending refunds can be marked collected.'}};if(l.varianceType!==LiquidationVarianceType.REFUND_DUE)return {status:400,body:{error:'No refund is due for this Liquidation.'}};if(!input.refundMethod||!state.systemSettings.paymentMethods.includes(input.refundMethod))return {status:400,body:{error:`Refund method must be one of: ${state.systemSettings.paymentMethods.join(', ')}`}};const ca=state.cashAdvances.find(x=>x.id===l.cashAdvanceId);const old=l.status;l.status=LiquidationStatus.CLOSED;if(ca)ca.status=CashAdvanceStatus.LIQUIDATED;(l as any).refundReference=input.referenceNote||'Collected by Custodian';(l as any).refundMethod=input.refundMethod;(l as any).refundCollectedAt=new Date().toISOString();addLiqHistory(id,old,l.status,user.id,`Closed (Refund Collected via ${input.refundMethod})`);try{await persistLiquidation(l);if(ca)await persistCashAdvance(ca)}catch(error){console.error('[db] Could not persist refund collection to Postgres:',error)}return {status:200,body:l}; }
